title: Linux System Administrator
description: Linux administration notes, commands, and practical guides

remote_theme: just-the-docs/just-the-docs

color_scheme: dark

search_enabled: true
heading_anchors: true

aux_links:
  "GitHub Repository":
    - "https://github.com/r-lakshman/Linux-System-Administrator"
